# ADLA CSC522
#### HW1
#### Group: H21
#### Karan Gala 
#### Sahil Sawant
#### Akhil Namboodiri

# Generate a 5*5 identity matrix A.

In [18]:
import numpy as np
A = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Change all elements in the 5th column of A to 5.

In [19]:
for i in range(5):
    A[i][4] = 5
A

array([[1, 0, 0, 0, 5],
       [0, 1, 0, 0, 5],
       [0, 0, 1, 0, 5],
       [0, 0, 0, 1, 5],
       [0, 0, 0, 0, 5]])

# Sum of all elements in the matrix (use ONE “for/while loop”).

In [20]:
sum = 0
for i in A:
    sum+=np.sum(i)
sum

29

In [21]:
sum2 = np.sum(A)
sum2

29

# Transpose the matrix A (A=AT ).

In [22]:
AT = np.transpose(A)
AT

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [5, 5, 5, 5, 5]])

In [23]:
AT = np.zeros((5,5))
for i in range(5):
  for j in range(5):
    AT[i][j] = A[j][i]
AT

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [5., 5., 5., 5., 5.]])

# Calculate the sum of the 5th row, the sum of the diagonal and the sum of the 1st column in matrix A, respectively (your answer should be three numbers). Use the transposed matrix from the previous part.

In [24]:
sum5 = np.sum(AT[4])
print("Sum of 5th row:", sum5)
sum1 = 0
for i in range(5):
    sum1+=AT[i][0]
print("Sum of 1st column:", sum1)
sumD = 0
for i in range(5):
    sumD+=AT[i][i]
print("Sum of Diagonal elements:", sumD)

Sum of 5th row: 25.0
Sum of 1st column: 6.0
Sum of Diagonal elements: 9.0


# Generate a 5*5 matrix B following standard normal distribution.

In [25]:
B = np.random.normal(3,0.5,(5,5))
B

array([[3.28530538, 2.51284604, 2.76503772, 2.91919723, 2.81374224],
       [3.01603991, 3.57112138, 3.05022633, 2.15185857, 2.33834881],
       [2.60862271, 3.69217796, 2.88162901, 2.62289769, 2.75506897],
       [3.79236804, 3.48991234, 3.30613709, 3.67041122, 2.05425629],
       [2.67106314, 3.16837451, 3.55316914, 3.84892862, 2.38779581]])

## From A and B, using matrix operations to get a new 2*5 matrix C such that, the first row of C is equal to the 1st row of B minus the 1st row of A, the second row of C is equal to the sum of the 5th row of A and the 5th row of B.

In [26]:
C = np.empty(shape = (2,5))
C[0] = B[0] - A[0]
C[1] = B[4] + A[4]
C

array([[ 2.28530538,  2.51284604,  2.76503772,  2.91919723, -2.18625776],
       [ 2.67106314,  3.16837451,  3.55316914,  3.84892862,  7.38779581]])

# From C, using ONE matrix operation to get a new matrix D such that,the first column of D is equal to the first column of C, the second column of D is equal to the second column of C times 2, the third column of D is equal to the third column of C times 3, and so on.

In [27]:
D = np.empty(shape = (5,2))
temp = np.transpose(C)
for i in range(5):
    D[i] = (i+1)*temp[i]
D = np.transpose(D)
D

array([[  2.28530538,   5.02569207,   8.29511316,  11.67678893,
        -10.93128881],
       [  2.67106314,   6.33674901,  10.65950743,  15.39571447,
         36.93897904]])

# X = [1, 1, 1, 2]T , Y = [0, 3, 6, 9]T , Z = [4, 3, 2, 1]T . Compute the covariance matrix of X, Y, and Z. Then compute the Pearson correlation coefficients between X and Y.

In [28]:
import numpy as np
X = np.array([[1],[1],[1],[2]])
Y = np.array([[0],[3],[6],[9]])
Z = np.array([[4],[3],[2],[1]])
covMatrix = np.cov(np.concatenate((X.T,Y.T,Z.T),axis = 0))
print("Covariance of matrix X,Y and Z:")
print(covMatrix)
print()
pc = np.corrcoef(X.T,Y.T)
print("Pearson Correlation Coefficients between X and Y:")
print(pc)

Covariance of matrix X,Y and Z:
[[ 0.25        1.5        -0.5       ]
 [ 1.5        15.         -5.        ]
 [-0.5        -5.          1.66666667]]

Pearson Correlation Coefficients between X and Y:
[[1.         0.77459667]
 [0.77459667 1.        ]]


# Verify the equation: ¯x 2 = (¯x2+σ2(x)) using x = [23, 19, 21, 22, 21, 23, 23, 20]T when (python library math is allowed): 
## i. σ(x) is the population standard  eviation. Show your work. 
## ii. σ(x) is the sample standard deviation. Show your work.

In [29]:
x = (np.array([23,19,21,22,21,23,23,20]))
meanX = np.average(x)
import statistics
sdXSample = statistics.stdev(x)
sdXPopulation = statistics.pstdev(x)
print(meanX,sdXPopulation,sdXSample)

21.5 1.4142135623730951 1.4142135623730951


In [30]:
popSD = 0
sampleSD = 0
n = len(x)
v = 0
v2 = 0
for i in x:
    v+=(meanX-i)*(meanX-i)/(n)
    v2+=(meanX-i)*(meanX-i)/(n-1)
popSD = v**0.5
sampleSD = v2**0.5
print("SD of population: \t",popSD)
print("SD of sample: \t\t",sampleSD)

SD of population: 	 1.4142135623730951
SD of sample: 		 1.511857892036909


In [31]:
meanXSq = meanX**2
meanXSq+popSD**2 #RHS

464.25

In [32]:
np.average(np.square(x)) #LHS

464.25

# LHS == RHS