# ADLA CSC522
#### HW1
#### Group: H21
#### Karan Gala 
#### Sahil Sawant
#### Akhil Namboodiri

# Generate a 5*5 identity matrix A.

In [1]:
import numpy as np
A = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])
print("A:",A)

A: [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Change all elements in the 5th column of A to 5.

In [2]:
for i in range(5):
    A[i][4] = 5
print("A:",A)

A: [[1 0 0 0 5]
 [0 1 0 0 5]
 [0 0 1 0 5]
 [0 0 0 1 5]
 [0 0 0 0 5]]


# Sum of all elements in the matrix (use ONE “for/while loop”).

In [3]:
sum = 0
for i in A:
    sum+=np.sum(i)
print("Sum of all elements in the matrix:",sum)

Sum of all elements in the matrix: 29


In [4]:
sum2 = np.sum(A)
print("Sum of all elements in the matrix:",sum2)

Sum of all elements in the matrix: 29


# Transpose the matrix A (A=AT ).

In [5]:
AT = np.transpose(A)
print("Transpose of A:",AT)

Transpose of A: [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [5 5 5 5 5]]


In [6]:
AT = np.zeros((5,5))
for i in range(5):
  for j in range(5):
    AT[i][j] = A[j][i]
print("Transpose of A:",AT)

Transpose of A: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [5. 5. 5. 5. 5.]]


# Calculate the sum of the 5th row, the sum of the diagonal and the sum of the 1st column in matrix A, respectively (your answer should be three numbers). Use the transposed matrix from the previous part.

In [7]:
sum5 = np.sum(AT[4])
print("Sum of 5th row:", sum5)
sum1 = 0
for i in range(5):
    sum1+=AT[i][0]
print("Sum of 1st column:", sum1)
sumD = 0
for i in range(5):
    sumD+=AT[i][i]
print("Sum of Diagonal elements:", sumD)

Sum of 5th row: 25.0
Sum of 1st column: 6.0
Sum of Diagonal elements: 9.0


# Generate a 5*5 matrix B following standard normal distribution.

In [8]:
B = np.random.normal(3,0.5,(5,5))
print("Matrix B:",B)

Matrix B: [[2.5452833  2.97915952 3.36415772 2.67618576 2.96693581]
 [2.78658079 2.81756899 3.36430994 3.10971939 2.86295184]
 [2.49374949 2.54239402 3.06640962 3.19225717 3.22737013]
 [2.81063256 3.59789933 3.08960295 2.92183558 2.27145742]
 [3.32917176 3.16415336 3.48238412 2.67411579 3.19037623]]


## From A and B, using matrix operations to get a new 2*5 matrix C such that, the first row of C is equal to the 1st row of B minus the 1st row of A, the second row of C is equal to the sum of the 5th row of A and the 5th row of B.

In [9]:
C = np.empty(shape = (2,5))
C[0] = B[0] - A[0]
C[1] = B[4] + A[4]
print("Matrix C:",C)

Matrix C: [[ 1.5452833   2.97915952  3.36415772  2.67618576 -2.03306419]
 [ 3.32917176  3.16415336  3.48238412  2.67411579  8.19037623]]


# From C, using ONE matrix operation to get a new matrix D such that,the first column of D is equal to the first column of C, the second column of D is equal to the second column of C times 2, the third column of D is equal to the third column of C times 3, and so on.

In [10]:
D = np.empty(shape = (5,2))
temp = np.transpose(C)
for i in range(5):
    D[i] = (i+1)*temp[i]
D = np.transpose(D)
print("D :",D)


D : [[  1.5452833    5.95831905  10.09247317  10.70474305 -10.16532097]
 [  3.32917176   6.32830672  10.44715235  10.69646317  40.95188114]]


# X = [1, 1, 1, 2]T , Y = [0, 3, 6, 9]T , Z = [4, 3, 2, 1]T . Compute the covariance matrix of X, Y, and Z. Then compute the Pearson correlation coefficients between X and Y.

In [11]:
import numpy as np
X = np.array([[1],[1],[1],[2]])
Y = np.array([[0],[3],[6],[9]])
Z = np.array([[4],[3],[2],[1]])
covMatrix = np.cov(np.concatenate((X.T,Y.T,Z.T),axis = 0))
print("Covariance of matrix X,Y and Z:")
print(covMatrix)
print()
pc = np.corrcoef(X.T,Y.T)
print("Pearson Correlation Coefficients between X and Y:")
print(pc, pc[0][1])

Covariance of matrix X,Y and Z:
[[ 0.25        1.5        -0.5       ]
 [ 1.5        15.         -5.        ]
 [-0.5        -5.          1.66666667]]

Pearson Correlation Coefficients between X and Y:
[[1.         0.77459667]
 [0.77459667 1.        ]] 0.7745966692414834


# Verify the equation: ¯x 2 = (¯x2+σ2(x)) using x = [23, 19, 21, 22, 21, 23, 23, 20]T when (python library math is allowed): 
## i. σ(x) is the population standard  eviation. Show your work. 
## ii. σ(x) is the sample standard deviation. Show your work.

In [12]:
x = (np.array([23,19,21,22,21,23,23,20]))
meanX = np.average(x)
import statistics
sdXSample = statistics.stdev(x)
sdXPopulation = statistics.pstdev(x)
print("Mean of X:", meanX)

Mean of X: 21.5


In [13]:
popSD = 0
sampleSD = 0
n = len(x)
v = 0
v2 = 0
for i in x:
    v+=(meanX-i)*(meanX-i)/(n)
    v2+=(meanX-i)*(meanX-i)/(n-1)
popSD = v**0.5
sampleSD = v2**0.5
print("SD of population: \t",popSD)
print("SD of sample: \t\t",sampleSD)

SD of population: 	 1.4142135623730951
SD of sample: 		 1.511857892036909


In [14]:
meanXSq = meanX**2
print("Mean Squared with population standard deviation squared: ",meanXSq+popSD**2) #RHS
print("Mean Squared with population standard deviation squared: ",meanXSq+sampleSD**2)

Mean Squared with population standard deviation squared:  464.25
Mean Squared with population standard deviation squared:  464.5357142857143


In [15]:
print("Mean of sum of data points square: ",np.average(np.square(x))) #LHS

Mean of sum of data points square:  464.25


## The equation can be verified for the population standard deviation